---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: posijon/slci

inputs:
  - name: bosh-linux-stemcell-builder
  - name: stemcell
  - name: version

run:
  path: bosh-linux-stemcell-builder/ci/tasks/convert-stemcell.sh
