---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh

inputs:
  - name: bosh-softlayer-tools
  - name: stemcell-info
  - name: version
outputs:
  - name: light-stemcell

run:
  path: bosh-linux-stemcell-builder/ci/tasks/create-light-stemcell.sh
