---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh

inputs:
  - name: version
  - name: bosh-linux-stemcell-builder
  - name: bosh-softlayer-tools

outputs:
  - name: stemcell-image
run:
  path: bosh-linux-stemcell-builder/ci/tasks/import-stemcell.sh
